if(NOT DEFINED INPUT OR INPUT STREQUAL "")
    message(FATAL_ERROR "GenerateMenuHelpHeader.cmake requires -DINPUT=<path>")
endif()

if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
    message(FATAL_ERROR "GenerateMenuHelpHeader.cmake requires -DOUTPUT=<path>")
endif()

if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "Menu-help input file does not exist: ${INPUT}")
endif()

function(decode_menuhelp_text encoded line_number result_variable)
    set(decoded "")
    string(LENGTH "${encoded}" encoded_length)
    set(index 0)
    while(index LESS encoded_length)
        string(SUBSTRING "${encoded}" ${index} 1 character)
        if(NOT character STREQUAL [[\]])
            string(APPEND decoded "${character}")
            math(EXPR index "${index} + 1")
            continue()
        endif()

        math(EXPR index "${index} + 1")
        if(index GREATER_EQUAL encoded_length)
            message(FATAL_ERROR
                "Malformed menu-help escape on line ${line_number}: trailing backslash")
        endif()

        string(SUBSTRING "${encoded}" ${index} 1 escaped_character)
        if(escaped_character STREQUAL [[\]] OR escaped_character STREQUAL [["]])
            string(APPEND decoded "${escaped_character}")
        elseif(escaped_character STREQUAL "n")
            string(APPEND decoded "\n")
        elseif(escaped_character STREQUAL "r")
            string(APPEND decoded "\r")
        elseif(escaped_character STREQUAL "t")
            string(APPEND decoded "\t")
        else()
            message(FATAL_ERROR
                "Unsupported menu-help escape on line ${line_number}: \\${escaped_character}")
        endif()
        math(EXPR index "${index} + 1")
    endwhile()

    set(${result_variable} "${decoded}" PARENT_SCOPE)
endfunction()

file(STRINGS "${INPUT}" menuhelp_lines ENCODING UTF-8)

set(entries "")
set(entry_count 0)
set(line_number 0)
foreach(line IN LISTS menuhelp_lines)
    math(EXPR line_number "${line_number} + 1")
    string(REPLACE "\r" "" line "${line}")
    string(REPLACE "\t" " " line "${line}")
    string(STRIP "${line}" line)

    if(line STREQUAL "" OR line MATCHES "^;")
        continue()
    endif()

    if(NOT line MATCHES [[^x, *"(([^"\\]|\\.)*)" *$]])
        message(FATAL_ERROR
            "Malformed menu-help record on line ${line_number}: ${line}")
    endif()

    decode_menuhelp_text("${CMAKE_MATCH_1}" ${line_number} menuhelp_text)
    string(REPLACE [[\]] [[\\]] menuhelp_text "${menuhelp_text}")
    string(REPLACE [["]] [[\"]] menuhelp_text "${menuhelp_text}")
    string(APPEND entries "    \"${menuhelp_text}\",\n")
    math(EXPR entry_count "${entry_count} + 1")
endforeach()

if(entry_count EQUAL 0)
    message(FATAL_ERROR "Menu-help input did not contain any data records: ${INPUT}")
endif()

set(content "/* This file was created by GenerateMenuHelpHeader.cmake.  Do Not Edit! */\n\n")
string(APPEND content "#ifdef OPUS_X64\n")
string(APPEND content "static char * const rgszOpusX64MenuHelp[] = {\n")
string(APPEND content "${entries}")
string(APPEND content "};\n")
string(APPEND content "#define OPUS_X64_MENU_HELP_STRING(iidstr) \\\n    (((unsigned int)(iidstr) < (unsigned int)(sizeof(rgszOpusX64MenuHelp) / sizeof(rgszOpusX64MenuHelp[0]))) \\\n        ? rgszOpusX64MenuHelp[(unsigned int)(iidstr)] : \"\")\n")
string(APPEND content "#endif\n")

get_filename_component(output_directory "${OUTPUT}" DIRECTORY)
if(NOT output_directory STREQUAL "")
    file(MAKE_DIRECTORY "${output_directory}")
endif()

set(should_write TRUE)
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing_content)
    if(existing_content STREQUAL content)
        set(should_write FALSE)
    endif()
endif()

if(should_write)
    file(WRITE "${OUTPUT}" "${content}")
endif()
