if(NOT DEFINED INPUT)
    message(FATAL_ERROR "INPUT is required")
endif()
if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()
if(NOT DEFINED DATA_OUTPUT)
    message(FATAL_ERROR "DATA_OUTPUT is required")
endif()

file(READ "${INPUT}" content)
string(REGEX MATCHALL "/export:[A-Za-z_][A-Za-z0-9_]*" exports "${content}")
string(REGEX REPLACE "#pragma comment\\(linker, \"/export:[A-Za-z_][A-Za-z0-9_]*\"\\)\n" "" data "${content}")

set(names)
foreach(export ${exports})
    string(REGEX REPLACE "^/export:" "" name "${export}")
    list(APPEND names "${name}")
endforeach()
list(REMOVE_DUPLICATES names)
list(SORT names)
list(LENGTH names name_count)
if(name_count EQUAL 0)
    message(FATAL_ERROR "No command exports found in ${INPUT}")
endif()

set(output "/* Generated from opuscmd_native.inc. */\n")
foreach(name ${names})
    string(APPEND output "extern int ${name}();\n")
endforeach()
string(APPEND output "\nstatic const OpusNativeCommandAddress kOpusNativeCommandAddresses[] = {\n")
foreach(name ${names})
    string(APPEND output " { \"${name}\", (OPUS_PFN)${name} },\n")
endforeach()
string(APPEND output "};\n")

file(WRITE "${DATA_OUTPUT}" "${data}")
file(WRITE "${OUTPUT}" "${output}")
