function(append_resource_array output_var name input)
    file(READ "${input}" bytes HEX)
    string(LENGTH "${bytes}" hex_length)
    set(initializer "")
    set(index 0)
    while(index LESS hex_length)
        math(EXPR column "(${index} / 2) % 12")
        if(column EQUAL 0)
            string(APPEND initializer "    ")
        endif()
        string(SUBSTRING "${bytes}" ${index} 2 byte)
        string(APPEND initializer "0x${byte}, ")
        if(column EQUAL 11)
            string(APPEND initializer "\n")
        endif()
        math(EXPR index "${index} + 2")
    endwhile()
    if(NOT initializer MATCHES "\n$")
        string(APPEND initializer "\n")
    endif()
    set(updated "${${output_var}}")
    string(APPEND updated
        "OPUS_WIN32_RESOURCE_ARRAY unsigned char ${name}[] = {\n${initializer}};\n"
        "OPUS_WIN32_RESOURCE_ARRAY unsigned int ${name}_size = sizeof(${name});\n\n")
    set(${output_var} "${updated}" PARENT_SCOPE)
endfunction()

set(content "/* THIS IS A GENERATED FILE -- DO NOT EDIT */\n#pragma once\n\n#ifdef __cplusplus\n#define OPUS_WIN32_RESOURCE_ARRAY inline constexpr\n#else\n#define OPUS_WIN32_RESOURCE_ARRAY static const\n#endif\n\n")
append_resource_array(content "kOpusToolbar201Bmp" "${TOOLBAR_BMP}")
append_resource_array(content "kOpusIcon301Ico" "${ICON_301}")
append_resource_array(content "kOpusIcon302Ico" "${ICON_302}")
string(APPEND content "#undef OPUS_WIN32_RESOURCE_ARRAY\n")
file(WRITE "${OUTPUT}" "${content}")
