#include "cmd.h"
#include "IBCM.H"

int main(void)
{
    /* Values are generated by Microsoft's original MKCMD parser from
     * opuscmd.cmd.  These are offsets in the expanded native symbol table;
     * IBCM remains the original compatibility-map index. */
    if (bcmCut != (sizeof(void *) == 4 ? 1896 : 2252) ||
        bcmCopy != (sizeof(void *) == 4 ? 1914 : 2274))
        return 1;
    if (ibcmEditCut != 86 || ibcmEditCopy != 87)
        return 2;
    if (bcmMacStd != (sizeof(void *) == 4 ? 9531 : 11247))
        return 3;
    return 0;
}
